### PR TITLE
Hotfix packagelockjson

### LINKED ISSUE #21: 20 nov : package.lock.json is not complete
## Bug Report

**Current Behavior**
doesn't work on download

**Expected behavior/code**
download and just works

**Possible Solution**
update node and npm, update package.lock.json and install fontawesome then hot fixe the dev branch

### PR DESCRIPTION
**Pull request by kataya1**
Fixes #21

### CODE REVIEW

**Comment by HassanTAli** [comment]
how many pull request do you need?
Kataya : Yes

**Review by HassanTAli — COMMENTED** [review]
w ana kamen review aho

**Comment by kataya1** [comment]
this is a hotfix for the dev branch. @HassanTAli why close ?.

**Review by bruno-0 — COMMENTED** [review]
🤝

**Pull request merged**
